version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    working_directory: ~/application
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Package
          command: 'yarn install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: repo-$CIRCLE_BUILD_NUM-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/application
  build_and_deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/application
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - restore_cache:
          key: repo-$CIRCLE_BUILD_NUM-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Deploy TEST
          command: 'yarn build && yarn deploy'

workflows:
  version: 2.1
  commit_build:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - build_and_deploy:
          requires:
            - setup
          context: aws